# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 12:38
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=10, verbose_name='\u6027\u522b')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/%Y/%m', verbose_name='\u56fe\u7247')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u53d1\u5e03\u4eba\u59d3\u540d')),
                ('image', models.ImageField(upload_to='author/%Y/%m', verbose_name='\u5934\u50cf')),
                ('position', models.CharField(max_length=50, verbose_name='\u804c\u4f4d')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u4eba',
                'verbose_name_plural': '\u53d1\u5e03\u4eba',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u8f6e\u64ad\u56fe\u7247\u540d\u79f0')),
                ('homeImage', models.ImageField(upload_to='images/%Y/%m', verbose_name='\u8f6e\u64ad\u56fe')),
                ('homeImageSmall', models.ImageField(upload_to='images/%Y/%m', verbose_name='\u5c0f\u8f6e\u64ad\u56fe')),
                ('recommend_Image', models.ImageField(upload_to='images/%Y/%m', verbose_name='\u9762\u5305\u5c51\u63a8\u8350\u56fe')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('salary', models.CharField(choices=[('s1', '2k\u4ee5\u4e0b'), ('s2', '2k-5k'), ('s3', '5k-10k'), ('s4', '10k-15k'), ('s5', '15k-25k'), ('s6', '25k-50k'), ('s7', '50k\u4ee5\u4e0a')], default='s4', max_length=20, verbose_name='\u85aa\u8d44')),
                ('education', models.CharField(choices=[('e1', '\u4e0d\u9650'), ('e2', '\u4e2d\u4e13\u53ca\u4ee5\u4e0b'), ('e3', '\u9ad8\u4e2d'), ('e4', '\u5927\u4e13'), ('e5', '\u672c\u79d1'), ('e6', '\u7855\u58eb'), ('e7', '\u535a\u58eb')], default='e1', max_length=20, verbose_name='\u5b66\u5386')),
                ('des', models.CharField(max_length=20, verbose_name='\u804c\u4f4d\u63cf\u8ff0')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9')),
                ('workType', models.CharField(choices=[('w1', '\u4e0d\u9650'), ('w2', '\u5168\u804c'), ('w3', '\u517c\u804c'), ('w4', '\u5b9e\u4e60')], default='w1', max_length=20, verbose_name='\u5de5\u4f5c\u6027\u8d28')),
                ('image', models.ImageField(upload_to='interview/%Y/%m', verbose_name='\u56fe\u7247')),
                ('company', models.CharField(max_length=50, verbose_name='\u516c\u53f8')),
                ('yearsRequire', models.CharField(choices=[('y1', '\u4e0d\u9650'), ('y2', '\u5e94\u5c4a\u751f'), ('y3', '1\u5e74\u4ee5\u5185'), ('y4', '1-3\u5e74'), ('y5', '3-5\u5e74'), ('y6', '5-10\u5e74'), ('y7', '10\u5e74\u4ee5\u4e0a')], default='y1', max_length=20, verbose_name='\u5de5\u4f5c\u7ecf\u9a8c')),
                ('trade', models.CharField(choices=[('t1', '\u6280\u672f'), ('t2', '\u4ea7\u54c1'), ('t3', '\u8bbe\u8ba1'), ('t4', '\u8fd0\u8425'), ('t5', '\u5e02\u573a\u9500\u552e'), ('t6', '\u804c\u80fd'), ('t7', '\u91d1\u878d'), ('t8', '\u6587\u6848\u516c\u5173'), ('t9', '\u6559\u5e08'), ('t10', '\u6821\u62db')], default='t1', max_length=10, verbose_name='\u884c\u4e1a')),
                ('domain', models.CharField(max_length=20, verbose_name='\u516c\u53f8\u9886\u57df')),
                ('scale', models.CharField(choices=[('s1', '\u4e0d\u9650'), ('s2', '0-19\u4eba'), ('s3', '20-99\u4eba'), ('s4', '100-499\u4eba'), ('s5', '500-999\u4eba'), ('s6', '1000-9999\u4eba'), ('s7', '10000\u4eba\u4ee5\u4e0a')], default='s1', max_length=20, verbose_name='\u516c\u53f8\u89c4\u6a21')),
                ('moment', models.CharField(choices=[('m1', '\u4e0d\u9650'), ('m2', '\u672a\u878d\u8d44'), ('m3', '\u5929\u4f7f\u8f6e'), ('m4', 'A\u8f6e'), ('m5', 'B\u8f6e'), ('m6', 'C\u8f6e'), ('m7', 'D\u8f6e'), ('m8', 'D\u8f6e\u4ee5\u4e0a'), ('m9', '\u5df2\u4e0a\u5e02'), ('m10', '\u4e0d\u9700\u8981\u878d\u8d44')], default='m1', max_length=10, verbose_name='\u76ee\u524d\u516c\u53f8\u9636\u6bb5')),
                ('companyHome', models.URLField(max_length=100, verbose_name='\u516c\u53f8\u9996\u9875')),
                ('welfare1', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u516c\u53f8\u798f\u52291')),
                ('welfare2', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u516c\u53f8\u798f\u52292')),
                ('welfare3', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u516c\u53f8\u798f\u52293')),
                ('location', models.CharField(choices=[('l1', '\u5317\u4eac'), ('l2', '\u4e0a\u6d77'), ('l3', '\u5929\u6d25'), ('l4', '\u5e7f\u5dde'), ('l5', '\u676d\u5dde'), ('l6', '\u6df1\u5733'), ('l7', '\u5176\u4ed6')], default='l1', max_length=10, verbose_name='\u5de5\u4f5c\u5730\u533a')),
                ('map', models.URLField(max_length=100, verbose_name='\u5de5\u4f5c\u5730\u56fe')),
                ('pub_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('read_counts', models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u6b21\u6570')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Author', verbose_name='\u6240\u5c5e\u53d1\u5e03\u4eba')),
            ],
            options={
                'verbose_name': '\u8be6\u60c5',
                'verbose_name_plural': '\u8be6\u60c5',
            },
        ),
    ]
