# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='homeImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m', verbose_name='\u8f6e\u64ad\u56fe'),
        ),
        migrations.AlterField(
            model_name='image',
            name='homeImageSmall',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m', verbose_name='\u5c0f\u8f6e\u64ad\u56fe'),
        ),
        migrations.AlterField(
            model_name='image',
            name='recommend_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m', verbose_name='\u9762\u5305\u5c51\u63a8\u8350\u56fe'),
        ),
    ]
